apiVersion: v1
kind: Service
metadata:
  name: sse-chat
spec:
  selector:
    app: sse-chat
  ports:
    - port: 80
      targetPort: 5050
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sse-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sse-chat
  template:
    metadata:
      labels:
        app: sse-chat
    spec:
      containers:
        - name: sse-chat
          image: registry.digitalocean.com/samwise-gamgee/sse-chat:v1.0.1-0
          env:
            - name: CORS_ALLOW_ORIGIN
              value: "https://saasclerk.com/"
          ports:
            - containerPort: 5050
          imagePullPolicy: Always