[package]
name = "hlf"
version = "0.1.0"
authors = ["Aleksandar Chalakov <a.chalakov@codefoundries.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.5.0", features = ["macros", "rt-multi-thread"] }

parking_lot = "0.11"
log = "0.4"
