[package]
name = "backend-rust"
version = "0.1.0"
authors = ["Aleksandar Chalakov <a.chalakov@codefoundries.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.14"
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.64"
tokio = { version = "1.5.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.5"

# bytes = "0.4.12"
parking_lot = "0.11"
log = "0.4"
pretty_env_logger = "0.4.0"
